steps:
# Install dependencies
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
# Test the code
- name: 'node'
  entrypoint: 'npm'
  args: ['test']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello_world:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello_world:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hello_world'
  - '--image'
  - 'gcr.io/$PROJECT_ID/hello_world:$COMMIT_SHA'
  - '--region'
  - 'REGION'
images:
- 'gcr.io/$PROJECT_ID/hello_world:$COMMIT_SHA'